Repository taskolib/taskolib, pull requests merged in 2022-11, with the labels that each got.

#36 Remove .vscode/settings.json and add it to .gitignore
  .gitignore
  .vscode/settings.json
Labels: cleanup

#39 Sol: Fix clang compiler warning
  include/taskolib/sol/sol/sol.hpp
  src/Step.cc
Labels: enhancement

#17 Create action pipeline for automatic build and test on push
  .github/workflows/build_and_run_tests.yml
  .gitignore
  meson.build
Labels: enhancement

#44 CI: Make error logs availabe if CI fails
  .github/workflows/build_and_run_tests.yml
Labels: enhancement, CI

#46 Test only strictly guaranteed conditions
  tests/test_Executor.cc
Labels: bug

#33 Step: Add bool and nil context variable types
  include/taskolib/Context.h
  src/Step.cc
  tests/test_Context.cc
  tests/test_Sequence.cc
  tests/test_Step.cc
Labels: enhancement
